const issueListDummy = () => {
  return [
    {
      idx: 1,
      author: 'Camper1',
      title: 'title1',
      createdTime: '2020-10-27T09:52:39.000Z',
      closedTime: null,
      status: true,
      milestoneIdx: 'frontEnd',
      labelTitle: 'FE',
      labelColor: 'red',
    },
    {
      idx: 2,
      author: 'Camper1',
      title: 'title2',
      createdTime: '2020-10-27T09:52:39.000Z',
      closedTime: null,
      status: true,
      milestoneIdx: 'frontEnd',
      labelTitle: 'FE',
      labelColor: 'red',
    },
    {
      idx: 3,
      author: 'Camper1',
      title: 'title3',
      createdTime: '2020-10-27T09:52:39.000Z',
      closedTime: null,
      status: true,
      milestoneIdx: 'frontEnd',
      labelTitle: 'FE',
      labelColor: 'red',
    },
    {
      idx: 4,
      author: 'Camper1',
      title: 'title4',
      createdTime: '2020-10-27T09:52:39.000Z',
      closedTime: null,
      status: true,
      milestoneIdx: 'frontEnd',
      labelTitle: 'FE',
      labelColor: 'red',
    },
    {
      idx: 5,
      author: 'Camper1',
      title: 'title5',
      createdTime: '2020-10-27T09:52:39.000Z',
      closedTime: null,
      status: true,
      milestoneIdx: 'backEnd',
      labelTitle: 'FE',
      labelColor: 'red',
    },
    {
      idx: 6,
      author: 'Booster',
      title: 'title6',
      createdTime: '2020-10-27T09:52:39.000Z',
      closedTime: null,
      status: true,
      milestoneIdx: 'frontEnd',
      labelTitle: 'FE',
      labelColor: 'red',
    },
    {
      idx: 7,
      author: 'Booster',
      title: 'title7',
      createdTime: '2020-10-27T09:52:39.000Z',
      closedTime: null,
      status: true,
      milestoneIdx: 'frontEnd',
      labelTitle: 'FE',
      labelColor: 'red',
    },
    {
      idx: 8,
      author: 'Booster',
      title: 'title8',
      createdTime: '2020-10-27T09:52:39.000Z',
      closedTime: '2020-10-27T09:52:39.000Z',
      status: true,
      milestoneIdx: 'backEnd',
      labelTitle: 'FE',
      labelColor: 'red',
    },
  ];
};

export default issueListDummy;
